/**
 * ExerciseLoader
 *
 * Fetches book and exercise content from the books/ folder and manages
 * pushing the starting code to the device.
 *
 * Exercise paths have the form:  books/{bookId}/{chapterId}/{labId}
 */

const BOOKS_BASE = 'books';

export class ExerciseLoader {
  constructor(repl) {
    this.repl = repl;
    this._cache = {};
  }

  /**
   * Return the master book list from books/index.json.
   * Shape: { books: [{ id, title, description, chapters, labs }] }
   */
  async loadBooksIndex() {
    const res = await fetch(`${BOOKS_BASE}/index.json`);
    return res.json();
  }

  /**
   * Return the full index for one book from books/{bookId}/index.json.
   * Shape: { id, title, description, chapters: [{ id, title, labs: [{ id, title, desc }] }] }
   */
  async loadBook(bookId) {
    const res = await fetch(`${BOOKS_BASE}/${bookId}/index.json`);
    return res.json();
  }

  /**
   * Load all content for one exercise given its full path.
   * exercisePath example: "books/clb-teaching/ch1-hardware-basics/ch1_lab1_getting_started"
   *
   * Returns { meta, pages, files, tutor, base } where:
   *   pages — array of markdown strings, one per description page
   *   files — array of { spec, startCode, solutionCode }, one per edit_files entry
   *   base  — the exercisePath (used for constructing relative asset URLs)
   */
  async loadExercise(exercisePath) {
    if (this._cache[exercisePath]) return this._cache[exercisePath];

    const base = exercisePath;
    const meta = await fetch(`${base}/exercise.json`).then(r => r.json());

    const pageFiles = meta.pages ?? ['description.md'];
    const [pages, tutor] = await Promise.all([
      Promise.all(pageFiles.map(f => fetch(`${base}/${f}`).then(r => r.text()))),
      fetch(`${base}/tutor.py`).then(r => r.text()).catch(() =>
        fetch(`${base}/tutor.json`).then(r => r.json()).then(j => j.tutor_brief).catch(() => null)
      ),
    ]);

    const editFiles = meta.edit_files !== undefined ? meta.edit_files : [{
      label: `${meta.start_file}.py`,
      source: 'start.py',
      solution: 'solution.py',
      device_path: `/managers/${meta.start_file}_manager.py`,
    }];

    const files = await Promise.all(editFiles.map(async spec => {
      const [startCode, solutionCode] = await Promise.all([
        fetch(`${base}/${spec.source}`).then(r => r.text()),
        spec.solution
          ? fetch(`${base}/${spec.solution}`).then(r => r.text()).catch(() => null)
          : Promise.resolve(null),
      ]);
      return { spec, startCode, solutionCode };
    }));

    const exercise = { meta, pages, files, tutor, base };
    this._cache[exercisePath] = exercise;
    return exercise;
  }

  /**
   * Push all of an exercise's files to the device, write app_manifest.py,
   * and write settings.json from the default_settings in exercise.json.
   */
  async setupExercise(exercise) {
    const { meta, files } = exercise;

    for (const { spec, startCode } of files) {
      await this.repl.writeFile(spec.device_path, startCode);
    }

    if (meta.clb !== false) {
      const manifest = this._buildManifest(meta);
      await this.repl.writeFile('/app_manifest.py', manifest);

      if (meta.default_settings) {
        await this.repl.writeFile('/settings.json', JSON.stringify(meta.default_settings));
      }
    }
  }

  _buildManifest(meta) {
    return [
      '# Auto-generated by CLB Teaching — do not edit by hand',
      'APPS = [',
      '    {',
      `        "name": ${JSON.stringify(meta.title)},`,
      `        "file": ${JSON.stringify(meta.start_file)},`,
      `        "desc": ${JSON.stringify(meta.circuit_description ?? '')},`,
      '    },',
      ']',
    ].join('\n') + '\n';
  }
}
