/**
 * ExerciseLoader
 *
 * Fetches exercise content from the exercises/ folder and manages
 * pushing the starting code to the device.
 */

const EXERCISES_BASE = '../exercises';

export class ExerciseLoader {
  constructor(repl) {
    this.repl = repl;
    this._cache = {};
  }

  /**
   * Return the ordered list of exercises from exercises/index.json.
   */
  async listExercises() {
    const res = await fetch(`${EXERCISES_BASE}/index.json`);
    return res.json();
  }

  /**
   * Load all content for one exercise.
   * Returns { meta, pages, files, tutor, base } where:
   *   pages — array of markdown strings, one per description page
   *   files — array of { spec, startCode, solutionCode }, one per edit_files entry
   * meta.pages lists filenames; falls back to ['description.md'] if absent.
   * Falls back to start_file/solution_file if edit_files is absent.
   */
  async loadExercise(id) {
    if (this._cache[id]) return this._cache[id];

    const base = `${EXERCISES_BASE}/${id}`;
    const meta = await fetch(`${base}/exercise.json`).then(r => r.json());

    const pageFiles = meta.pages ?? ['description.md'];
    const [pages, tutor] = await Promise.all([
      Promise.all(pageFiles.map(f => fetch(`${base}/${f}`).then(r => r.text()))),
      fetch(`${base}/tutor.json`).then(r => r.json()).catch(() => null),
    ]);

    const editFiles = meta.edit_files ?? [{
      label: `${meta.start_file}.py`,
      source: 'start.py',
      solution: 'solution.py',
      device_path: `/managers/${meta.start_file}_manager.py`,
    }];

    const files = await Promise.all(editFiles.map(async spec => {
      const [startCode, solutionCode] = await Promise.all([
        fetch(`${base}/${spec.source}`).then(r => r.text()),
        spec.solution
          ? fetch(`${base}/${spec.solution}`).then(r => r.text()).catch(() => null)
          : Promise.resolve(null),
      ]);
      return { spec, startCode, solutionCode };
    }));

    const exercise = { meta, pages, files, tutor, base };
    this._cache[id] = exercise;
    return exercise;
  }

  /**
   * Push all of an exercise's files to the device, write app_manifest.py,
   * and write settings.json from the default_settings in exercise.json.
   */
  async setupExercise(exercise) {
    const { meta, files } = exercise;

    for (const { spec, startCode } of files) {
      await this.repl.writeFile(spec.device_path, startCode);
    }

    const manifest = this._buildManifest(meta);
    await this.repl.writeFile('/app_manifest.py', manifest);

    if (meta.default_settings) {
      await this.repl.writeFile('/settings.json', JSON.stringify(meta.default_settings));
    }
  }

  _buildManifest(meta) {
    return [
      '# Auto-generated by CLB Teaching — do not edit by hand',
      'APPS = [',
      '    {',
      `        "name": ${JSON.stringify(meta.title)},`,
      `        "file": ${JSON.stringify(meta.start_file)},`,
      `        "desc": ${JSON.stringify(meta.circuit_description ?? '')},`,
      '    },',
      ']',
    ].join('\n') + '\n';
  }
}
